#ifndef __LOLIROFLE_NOTES_EXIT_H_INCLUDED__
#define __LOLIROFLE_NOTES_EXIT_H_INCLUDED__

//Exit codes
#define EXIT_ALLOCATION_FAILURE        54
#define EXIT_INPUT_ERROR               13
#define EXIT_ITEMENTRYCREATION_FAILURE 14
#define EXIT_UNKNOWN_ITEMDATATYPE      10

#endif
